services:
  backstage:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # - "3000:3000"
      - "7007:7007"
    environment:
      NODE_ENV: development
      NODE_OPTIONS: --no-node-snapshot
