apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: eks-cluster-template
  title: Deploy EKS Cluster with kro
  description: Creates a new EKS cluster. v20
spec:
  owner: user:guest
  type: service
  parameters:
    - title: EKS Cluster Information
      required:
        - clusterName
        - accountId
        - repoHostUrl
        - repoName
      properties:
        clusterName:
          title: EKS Cluster Name
          type: string
          description: Name of the EKS cluster
          ui:autofocus: true
        accountId:
          title: Account ID
          type: string
          description: AWS Account ID
        repoHostUrl:
          title: Repository host URL
          type: string
          description: Gitlab repository URL where the clusters-ns.yaml is located
          default: dvver71zswtj8.cloudfront.net
        repoName:
          title: Repository name
          type: string
          description: Gitea repository name where the clusters-ns.yaml is located
          default: eks-cluster-mgmt
  
  steps:
    - id: checkout
      name: Checkout repository
      action: fetch:plain
      input:
        url: https://${{ parameters.repoHostUrl }}/user1/${{ parameters.repoName }}/-/blob/main/
        targetPath: ./repo

    # - id: debug-log
    #   name: Log listWorkspace
    #   action: debug:log
    #   input:
    #     listWorkspace: true
    #     message: 'listWorkspace'
        
    # - id: mergeConfig
    #   name: Update Clusters Configuration
    #   action: roadiehq:utils:merge
    #   input:
    #     path: ./repo/addons/tenants/tenant1/default/addons/multi-acct/values.yaml
    #     content:
    #       clusters:
    #         '${{ parameters.clusterName }}': '${{ parameters.accountId }}'
    #     preserveYamlComments: true

    - id: addCluster
      name: Update Clusters Configuration
      action: roadiehq:utils:fs:append
      input:
        path: ./repo/addons/tenants/tenant1/default/addons/multi-acct/values.yaml
        content: '  ${{ parameters.clusterName }}: ${{ parameters.accountId }}'

    - id: parse
      name: read file
      action: roadiehq:utils:fs:parse
      input:
        path: ./repo/addons/tenants/tenant1/default/addons/multi-acct/values.yaml

    - id: log
      name: Console.log
      action: debug:log
      input:
        message: |
          Content: `${{ steps['parse'].output.content }}`

    # - id: pushChanges
    #   name: Push changes to Gitlab repository
    #   action: gitlab:repo:push
    #   input:
    #     repoUrl: ${{ parameters.repoHostUrl }}?repo=${{ parameters.repoName }}&owner=user1
    #     commitMessage: Add new EKS cluster
    #     branchName: main
    #     sourcePath: ./repo
    #     targetPath: .
      
    - id: createGitlabMergeRequest
      name: Create a Merge Request
      action: publish:gitlab:merge-request
      input:
        repoUrl: ${{ parameters.repoHostUrl }}?repo=${{ parameters.repoName }}&owner=user1
        title: Add new EKS cluster
        description: Add new EKS cluster to the platform
        sourcePath: ./repo
        targetPath: .
        branchName: new-cluster
        removeSourceBranch: true
        commitAction: auto

  output:
    links:
      - title: Gitlab MergeRequest URL
        url: ${{ steps.createGitlabMergeRequest.output.mergeRequestUrl }}
